export type PartOption =
  // Head
  | 'StandardVision'
  | 'InfraredVision'
  | 'NightVision'
  // Body
  | 'Square'
  | 'Round'
  | 'Triangular'
  | 'Rectangular'
  // Arms
  | 'Hands'
  | 'Pinchers'
  | 'BoxingGloves'
  // Movement
  | 'Wheels'
  | 'Legs'
  | 'Tracks'
  // Power
  | 'Solar'
  | 'RechargeableBattery'
  | 'Biomass';
